### ISSUE TITLE
Scraping Epic Games for Game description and reviews

### ISSUE THREAD

**Issue by ApoorvaGuptaaa** [Clueless-Community/scrape-up#290]
**Is your feature request related to a problem? Please describe.**
The suggested feature intends to offer a solution for accessing important details about games available on Epic Games, such as descriptions, current prices, and user ratings. This information can be utilized for price comparisons or training a predictive model to estimate future prices. Additionally, the current user ratings can assist users in gaining insights or establishing a ranking system through our library.

**Additional context**
Can be provided upon request.

I request @nikhil25803 to kindly assign this issue to me under GSSoC'23.

https://store.epicgames.com/en-US/

**Comment by hard02** [comment]
Sure @nikhil25803. I'll be glad to work with @ApoorvaGuptaaa on the issue. While @ApoorvaGuptaaa can work on Epic Games, I can continue the same on Steam. 

Just in case, Here's the website link for reference:
https://store.steampowered.com/

Please assign the issue to me as well @nikhil25803 :)

**Comment by nikhil25803** [comment]
Great !! @ApoorvaGuptaaa  will initiate the class (so that it won't conflict with yours) and he'll be working on scraping the top seller's games as well. You(@hard02 ) can work on the methods to scrape the following data.
![image](https://github.com/Clueless-Community/scrape-up/assets/93156825/32294f54-f6b7-49de-b539-aa27a70b0b1d)

**Comment by ApoorvaGuptaaa** [comment]
Thank you, sir. We'll start working right away.
