### ISSUE TITLE
BUG: test folder was deleted for different scrapers

### ISSUE THREAD

**Issue by Mihan786Chistie** [Clueless-Community/scrape-up#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

It seems that in the previously merged PR #374, the test folder has been deleted. I would like to contribute to restore the test folder. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Hey @Mihan786Chistie | I deleted the test folder because it was not appropriate, if you are willing the add test files, go ahead and add them for the `GitHub` class. 

**Note**
+ Covert test of each module of `GitHub` class in one defined class only.
+ For example - Add all the `Users` class and their methods in a single test class names `UserTest`.

Do let me know if you have any further doubts :))

**Comment by Mihan786Chistie** [comment]
@nikhil25803 will the userTest file be inside the GitHub folder?

**Comment by nikhil25803** [comment]
No @Mihan786Chistie | In the `scrape-up` folder, add a folder names `test`. In that create a file name `GitHubTest.py` and add your test script there.

**Comment by Mihan786Chistie** [comment]
> No @Mihan786Chistie | In the `scrape-up` folder, add a folder names `test`. In that create a file name `GitHubTest.py` and add your test script there.

Ohhh ok thanks
