### ISSUE TITLE
Feat: Scrape up Disney+ Hotstar Website

### ISSUE THREAD

**Issue by Tisha6661** [Clueless-Community/scrape-up#416]
### Describe the feature

Disney + Hotstar is one of the most famous website for movies, shows and cartoons I would like to scrape it for the data.

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/98682478/5c78e49c-3f17-4f2d-b2a9-292f44665de0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC 23 contributor
- [X] I want to work on this issue

**Comment by nikhil25803** [comment]
Hey @Tisha6661 | I can see another issue covering similar platform #415 |
Instead of creating separate modules for both, create one module and create files for each representing a separate class.
Eg
```python
ott_platform = OTT.DisneyPlusHotstar()
ott_platform.movies() # Or a method of your choice
```

**Note**
+ Separate file must be created for Hotstar and Jio Cinema (eg. `disney_plus_hotstar.py`)
+ Initialize classes in both files for the platforms.
+ Closing issue #415 for now, make 2 PRs, one after adding the Disney file and the other after adding Jio Cinema files.

**Comment by prateekboss4u** [comment]
Hey, I would like to work on this.

**Comment by nikhil25803** [comment]
Hey @prateekboss4u, this issue has already been assigned. 
Or, you can collab with @Tisha6661 , and make a new class for other OTTs other that she is covering. 
If this works, please raise a new issue regarding it.

**Comment by WhoIsJayD** [comment]
@Tisha6661 you still working on this?

**Comment by Tisha6661** [comment]
Yes I am working but it is getting a bit difficult, because I have tried BeautifulSoup library to do so, and whatever I scrape it is showing an empty list, so I am trying to work with different libraries now. But it is getting difficult and taking time, Still I am trying.

**Comment by prateekboss4u** [comment]
@Tisha6661 alright
can we work on it together if it's getting difficult?

**Comment by WhoIsJayD** [comment]
I can also work if you wish!
