### ISSUE TITLE
Feat: Goodreads Scrapping

### ISSUE THREAD

**Issue by NishthaJethani** [Clueless-Community/scrape-up#897]
### Describe the feature

As a part of GSSOC 24, I'd like to add a Goodreads module with the following functionalities:

1. Books read 
2. To Be Read books
3. Lists of books based on the tag

Please assign under the appropriate gssoc and level label.
Thanks!

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/95950571/ab08a1bf-a6a4-452b-91e9-82eb6d86352f)
![image](https://github.com/Clueless-Community/scrape-up/assets/95950571/160760d5-d2fa-4e19-ad55-226c7d2fca9d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Anshika14528** [comment]
Hello @NishthaJethani can i join you in creating this module?

**Comment by nikhil25803** [comment]
@Anshika14528 , I suggest you look for any other issue or module you want to add. Because I'll not be able to give points to both of you corresponding to a single PR.

-----

Go ahead @NishthaJethani 
**Note**
+ Please create a separate module for this, as in the folder and project structure (if it is not already created).
+ Do not use the `selenium web driver as it is incompatible with all devices and cloud platforms.
+ Before making any changes, please check whether the module you want to add exists. If yes, then you can add your functionality as a method only make a separate module and class for it.

All the best 👨‍💻
